//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonChinaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionOfChampionship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitionOfChampionship()
        {
            this.ModuleOfCompetitions = new HashSet<ModuleOfCompetition>();
            this.Registrations = new HashSet<Registration>();
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public Nullable<int> ChampionshipId { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual Competition Competition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleOfCompetition> ModuleOfCompetitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
