//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonChinaApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WSChina2020BaseComp01Entities : DbContext
    {
        public WSChina2020BaseComp01Entities()
            : base("name=WSChina2020BaseComp01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockSkill> BlockSkills { get; set; }
        public virtual DbSet<Championship> Championships { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<CompetitionOfChampionship> CompetitionOfChampionships { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<InfrastructureList> InfrastructureLists { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleOfCompetition> ModuleOfCompetitions { get; set; }
        public virtual DbSet<PhotoCompetition> PhotoCompetitions { get; set; }
        public virtual DbSet<PreviousCompetition> PreviousCompetitions { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduleCompetition> ScheduleCompetitions { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<SponsorClass> SponsorClasses { get; set; }
        public virtual DbSet<SponsorOfSponsorship> SponsorOfSponsorships { get; set; }
        public virtual DbSet<Sponsorship> Sponsorships { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
    }
}
