//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonChinaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoCompetition
    {
        public int Id { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> CompetitionId { get; set; }
    
        public virtual Competition Competition { get; set; }
    }
}
