//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonChinaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public int RegistrationId { get; set; }
        public double Quantity { get; set; }
        public int ModuleOfCompetitionId { get; set; }
    
        public virtual ModuleOfCompetition ModuleOfCompetition { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
