//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonChinaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsorship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sponsorship()
        {
            this.SponsorOfSponsorships = new HashSet<SponsorOfSponsorship>();
        }
    
        public int Id { get; set; }
        public double Amount { get; set; }
        public int SponsorClassId { get; set; }
    
        public virtual SponsorClass SponsorClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SponsorOfSponsorship> SponsorOfSponsorships { get; set; }
    }
}
